#!/usr/bin/env bash
set -eu
set -o pipefail

CPANM_URL="${CPANM_URL:-https://github.com/miyagawa/cpanminus/raw/1.7041/cpanm}"
CPANM_WGET="${WGET:-wget --no-check-certificate}"
CPANM_SHA1SUM="${CPANM_SHA1SUM-f680fb649127da5aa72912e3a2d1e130e38c9220}"

if [ -n "$CPANM_SHA1SUM" -a -f ./cpanminus ]; then
    echo "$CPANM_SHA1SUM  ./cpanminus" | sha1sum -c &>/dev/null || rm ./cpanminus
fi

if [ ! -f ./cpanminus ]; then
    $CPANM_WGET -O ./cpanminus "$CPANM_URL"
fi

if [ -n "$CPANM_SHA1SUM" ]; then
   sha1sum="$(sha1sum ./cpanminus | cut -f1 -d' ')"
   if [ "$sha1sum" != "$CPANM_SHA1SUM" ]; then
       echo "error: invalid sha1sum for cpanminus ($sha1sum), expected: $CPANM_SHA1SUM" >&2
       echo "       for downloaded file $CPANM_URL" >&2
       echo "       either update expected CPNAM_SHA1SUM in $0, or run as" >&2
       echo "       env CPANM_SHA1SUM='' $0 to disable check" >&2
       exit 1
   fi
fi
perl ./cpanminus App::cpanminus ${1+"$@"}
